
project_id = "bftuoerxiyocfputahrx"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = false

[studio]
enabled = false
port = 54323
api_url = "https://api.supabase.io"

[inbucket]
enabled = false
port = 54324

[storage]
enabled = false

[auth]
enabled = false
site_url = "http://localhost:3000"

[auth.email]
enabled = false
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enabled = false

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
vault_enabled = false

[functions]
[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-webhook-v2]
verify_jwt = false
